id: opecha:P001820
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24056
  title: གཙང་མྱང་སྨད་བསམ་འགྲུབ་རྩེའི་སྡེ་སྲིད་གཙང་པ་རིམ་བྱུང་གི་མངའ་ཐང་འབྱོར་རྒུད་ཀྱི་ལོ་རྒྱུས།
  volume: ''
  author: ''
